from docx import Document
from docx.shared import Inches
import pyttsx3

def speak(text):
    pyttsx3.speak(text)

cv = Document()

cv.add_picture('Anthony Felix Njuguna.jpg',width = Inches(1.0))

#Basic Information
name = input("Enter your Fullname: ")
speak('Hello ' + name + 'how you doing?')
speak('What is your phone number?')
phone_number = input("Enter your Phone No.: ")
email = input("Enter your email: ")

cv.add_paragraph(
    "Name: " + name + '\n' + 
    "Phone Number: " + phone_number + '\n' + 
    "Email: " + email
)
#Profile Summary
cv.add_heading("Profile Summary")
prof_summary = input("Tell Me about Yourself: ")
cv.add_paragraph (prof_summary)

#work experience
cv.add_heading('Work Experience')
work = cv.add_paragraph()
company = input('Enter Company: ')
from_date = input('Enter Start Date: ')
to_date = input('To Date: ')

#add text to existing paragraph
work.add_run(company + ": ").bold = True
work.add_run(from_date + " to " + to_date + "\n").italic = True

experience_details = input("Brief summary of experience at "+ company +": ")
work.add_run(experience_details)

#More Work experience
while True:
    more_experience = input("Do you have more experience? Yes or No ")
    if more_experience.lower()=='yes':
        work = cv.add_paragraph()
        company = input('Enter Company: ')
        from_date = input('Enter Start Date: ')
        to_date = input('To Date: ')

        #add text to existing paragraph
        work.add_run(company + ": ").bold = True
        work.add_run(from_date + " to " + to_date + "\n").italic = True

        experience_details = input("Brief summary of experience at "+ company +" ")
        work.add_run(experience_details)
    else:
        break

#Relevant skills
cv.add_heading("Relevant Skills").bold=True
skill_set = input("Please add Your Skills here: ")
skills = cv.add_paragraph(style='List Bullet')
skills.add_run(skill_set)

#more skills
while True:
    more_skills = input("Do You have more skills? Yes or No: ")
    if more_skills.lower() == "yes":
        skills = cv.add_paragraph(style='List Bullet')
        skill_set = input("Please add Your Skills here: ")
        skills.add_run(skill_set)
    else:
        break
#Footer Section
section = cv.sections[0]
footer = section.footer
p = footer.paragraphs[0]
p.text = "Resume auto-generated by Quick App"

cv.save('resume.docx')